import streamlit as st
import json
import os

def load_app_settings():
    """Load application settings from file"""
    settings_file = "data/app_settings.json"
    if os.path.exists(settings_file):
        try:
            with open(settings_file, 'r') as f:
                return json.load(f)
        except:
            pass
    return {'language': 'English', 'theme': 'Modern', 'offline_mode': False}

def save_app_settings(settings):
    """Save application settings to file"""
    settings_file = "data/app_settings.json"
    try:
        # Ensure data directory exists
        os.makedirs(os.path.dirname(settings_file), exist_ok=True)
        with open(settings_file, 'w') as f:
            json.dump(settings, f, indent=2)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def get_text(key, language=None):
    """Get localized text based on language setting"""
    # Get language from session state or settings if not provided
    if language is None:
        language = st.session_state.get('app_language')
        if language is None:
            settings = load_app_settings()
            language = settings.get('language', 'English')
            st.session_state['app_language'] = language
    
    translations = {
        'English': {
            # Navigation
            'dashboard': 'Dashboard',
            'prediction': 'Prediction', # Used in page_link
            'assessment': 'Assessment',  # Used in page_link and as form title
            'resources': 'Teacher Resources', # Full label for page_link
            'tracker': 'Parent Tracker', # Full label for page_link
            'analytics': 'Analytics', 
            'settings': 'Settings',   
            'educational_content': 'Educational Content', # Full label for page_link

            # Header & Global Status
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'Professional Learning Assessment Application',
            'system_status': 'System Status', 
            'online_mode': 'Online Mode', 
            'offline_mode': 'Offline Mode', 
            'toggle_offline_mode': 'Toggle Offline Mode', 
            'new_assessment_button': 'New Assessment', 

            # Dashboard - System Overview Stat Cards (Labels matching image text)
            'total_students_label': 'Total Students',
            'new_this_month_label': '↑ 12 new this month', 
            'on_track_label': 'On Track',
            'performing_well_label': '↑ 78% performing well', 
            'at_risk_label': 'At Risk',
            'need_support_label': '↑ 15% need support', 
            'intervention_label': 'Intervention',
            'urgent_attention_label': '↑ 7% urgent attention', 


            # Assessment Form
            'assessment_form': 'Assessment Form', 
            'empowering_student_success': 'Empowering Student Success',
            'student_information': 'Student Information',
            'student_name': 'Student Name',
            'grade_level': 'Grade Level',
            'teacher_name': 'Teacher Name', 
            'assessment_date': 'Assessment Date', 
            'academic_performance': 'Academic Performance',
            'behavioral_social_indicators': 'Behavioral & Social Indicators',
            'math_score': 'Math Score (0-100)',
            'reading_score': 'Reading Score (0-100)',
            'writing_score': 'Writing Score (0-100)',
            'attendance': 'School Attendance (%)',
            'behavior_rating': 'Behavior Rating (1-5)', 
            'literacy_level': 'Literacy Level (1-10)', 
            'analyze_learning_risk': 'Analyze Learning Risk',
            'clear_form': 'Clear Form',
            'assessment_results': 'AI Assessment Results',
            'comprehensive_assessment': 'Comprehensive learning assessment completed for',
            'risk_level': 'Risk Level',
            'recommendations': 'Recommendations',
            'low_risk': 'Low Risk',
            'medium_risk': 'Medium Risk',  
            'high_risk': 'High Risk',
            'confidence': 'Confidence',
            'teacher_notes': 'Teacher Notes',
            'prediction_saved_success': 'Prediction saved successfully!',
            'prediction_save_error': 'Error saving prediction.',
            'model_not_available': 'Model not available. Please check model files.',
            'error_making_prediction': 'Error making prediction:',
            'is_performing_well': 'is performing well. Continue current teaching methods.',
            'maintain_academic_support': 'Maintain current academic support',
            'consider_enrichment': 'Consider enrichment activities',
            'regular_monitoring': 'Regular progress monitoring',
            'may_need_additional_support': 'may need additional support.',
            'provide_targeted_interventions': 'Provide targeted interventions',
            'increase_one_on_one': 'Increase one-on-one support',
            'monitor_weekly': 'Monitor progress weekly',
            'requires_immediate_intervention': 'requires immediate intervention.',
            'implement_intensive_program': 'Implement intensive support program',
            'daily_monitoring': 'Daily progress monitoring',
            'consider_specialist': 'Consider specialist evaluation',
            
            # Teacher Resources
            'teacher_resources': 'Teacher Resources', 
            'supporting_every_teacher': 'Supporting Every Teacher, Reaching Every Student',
            'inclusive_classroom_excellence': 'Inclusive Classroom Excellence',
            'professional_development': 'Professional development resources designed for inclusive classroom success',
            'create_learning_environments': 'Create learning environments where every student thrives through differentiated instruction',
            'build_strong_partnerships': 'Build strong partnerships with families and specialists for comprehensive student support',
            'implement_culturally_responsive': 'Implement culturally responsive teaching methods that connect with Somali students',
            'use_multiple_assessment': 'Use multiple assessment methods to accurately gauge student progress and needs',
            'teaching_excellence_showcase': 'Teaching Excellence Showcase',
            'resource_categories': 'Resource Categories',
            'choose_resource_type': 'Choose resource type:',
            'differentiated_learning_strategies': 'Differentiated Learning Strategies',
            'inclusive_classroom_tips': 'Inclusive Classroom Tips',
            'intervention_techniques': 'Intervention Techniques',
            'assessment_strategies': 'Assessment Strategies',
            'activity_generator': 'Activity Generator',
            'teaching_strategies': 'Teaching Strategies', 
            'learning_activities': 'Learning Activities', 
            'assessment_tools': 'Assessment Tools', 
            'classroom_management': 'Classroom Management',
            'differentiation_techniques': 'Differentiation Techniques',
            'technology_integration': 'Technology Integration',
            'cultural_sensitivity': 'Cultural Sensitivity',
            'difficulty_focus': 'Difficulty Focus',
            'target_difficulty': 'Target difficulty:',
            'reading_language': 'Reading/Language',
            'mathematics': 'Mathematics',
            'writing': 'Writing',
            'attention_focus': 'Attention/Focus',
            'memory': 'Memory',
            'processing_speed': 'Processing Speed',
            'social_skills': 'Social Skills',
            'behavioral_issues': 'Behavioral Issues',
            'generate_teaching_strategy': 'Generate Teaching Strategy',
            'strategy_generated': 'Teaching Strategy Generated!',
            'interactive_learning_activities': 'Interactive Learning Activities',
            'generate_activity_ideas': 'Generate Activity Ideas',
            'activity_ideas_generated': 'Activity Ideas Generated!',
            'assessment_type': 'Assessment Type',
            'create_assessment': 'Create Assessment',
            'assessment_template_created': 'Assessment template created!',
            'clear_learning_objectives': 'Clear learning objectives defined',
            'multiple_question_formats': 'Multiple question formats included',
            'rubric_provided': 'Rubric for evaluation provided',
            'differentiated_difficulty': 'Differentiated difficulty levels available',
            'subject_area': 'Subject Area', 
            
            # Parent Tracker
            'parent_tracker': 'Parent Tracker', 
            'strengthening_connections': 'Strengthening Home-School Connections',
            'daily_observation_log': 'Daily Observation Log',
            'child_name': "Child's Name",
            'observation_date': 'Observation Date',
            'academic_observations': 'Academic Observations',
            'homework_completion': 'Homework Completion (%)',
            'reading_time': 'Reading Time (minutes)',
            'focus_level': 'Focus Level',
            'subjects_struggled': 'Subjects Struggled With',
            'behavioral_observations': 'Behavioral Observations', 
            'mood_rating': 'Mood Rating',
            'sleep_hours': 'Sleep Hours',
            'energy_level': 'Energy Level',
            'learning_wins': 'Learning Wins Today',
            'challenges_faced': 'Challenges Faced',
            'save_observation': 'Save Observation',
            'progress_insights': 'Progress Insights',
            'supporting_childs_learning': "Supporting Your Child's Learning Journey",
            'family_centered_approach': 'Family-Centered Approach to Educational Success',
            'empowering_parents_tools': 'Empowering parents with tools and insights to support their child\'s academic growth at home',
            'monitor_child_progress': 'Monitor your child\'s learning progress with simple, effective tools',
            'parent_empowerment': 'Parent Empowerment',
            'gain_insights_strategies': 'Gain insights and strategies to support learning at home',
            'school_partnership': 'School Partnership',
            'build_communication_bridges': 'Build strong communication bridges with your child\'s teachers',
            'student_success': 'Student Success',
            'celebrate_achievements': 'Celebrate achievements and address challenges together',
            'student_progress_stories': 'Student Progress Stories',
            'child_selection': 'Child Selection',
            'tracking': 'Tracking',
            'dashboard_options': 'Dashboard Options',
            'choose_view': 'Choose view:',
            'daily_entry': 'Daily Entry',
            'progress_tracking': 'Progress Tracking',
            'weekly_summary': 'Weekly Summary',
            'observations_log': 'Observations Log',
            'observation_saved_success': 'Observation saved successfully!',
            'observation_save_error': 'Error saving observation.',
            'no_observations_recorded': 'No observations recorded yet.',
            'error_loading_observations': 'Error loading observations:',
            'focus_level_trend': 'Focus Level Trend',
            'focus_level_over_time': 'Focus Level Over Time',
            'date': 'Date', 
            'behavioral_emotional': 'Behavioral & Emotional', 

            # Educational Content
            'educational_content': 'Educational Content', 
            'building_educational_excellence': 'Building Educational Excellence Through Research',
            'evidence_based_insights': 'Evidence-Based Insights for Learning Success',
            'comprehensive_educational_research': 'Comprehensive educational research and resources to support effective learning interventions',
            'educational_excellence_in_action': 'Educational Excellence in Action',
            'global_best_practices': 'Global Best Practices',
            'international_standards': 'International standards and methods adapted for Somali educational environments',
            'learning_science': 'Learning Science',
            'neuroscience_cognitive_research': 'Neuroscience and cognitive research on how children learn most effectively',
            'intervention_studies': 'Intervention Studies',
            'evidence_based_strategies': 'Evidence-based strategies for supporting students with learning challenges',
            'cultural_adaptation': 'Cultural Adaptation',
            'implementing_inclusive_education': 'Research on implementing inclusive education in diverse cultural contexts',
            'educational_research_impact': 'Educational Research Impact',
            'content_categories': 'Content Categories',
            'choose_content_type': 'Choose content type:',
            'research_overview': 'Research Overview',
            'types_learning_difficulties': 'Types of Learning Difficulties',
            'early_intervention': 'Early Intervention',
            'academic_resources': 'Academic Resources',
            'technology_tools': 'Technology Tools',
            'support_strategies': 'Support Strategies',
            'target_audience': 'Target Audience',
            'content_for': 'Content for:',
            'teachers': 'Teachers',
            'parents': 'Parents',
            'administrators': 'Administrators',
            'all': 'All',
            'understanding_learning_difficulties': 'Understanding Learning Difficulties',
            'learning_difficulties_affect_how': 'Learning difficulties affect how students process and understand information. Early identification and intervention are crucial for student success.',
            'common_types': 'Common Types:',
            'dyslexia': 'Dyslexia',
            'reading_difficulties': 'Reading difficulties',
            'dyscalculia': 'Dyscalculia',
            'math_difficulties': 'Math difficulties',
            'adhd': 'ADHD',
            'attention_difficulties': 'Attention difficulties',
            'processing_disorders': 'Processing disorders',
            'information_processing_issues': 'Information processing issues',
            'signs_to_watch_for': 'Signs to Watch For:',
            'difficulty_following_instructions': 'Difficulty following instructions',
            'problems_reading_comprehension': 'Problems with reading comprehension',
            'trouble_math_concepts': 'Trouble with math concepts',
            'difficulty_staying_focused': 'Difficulty staying focused',
            'problems_writing_spelling': 'Problems with writing and spelling',
            'evidence_based_interventions': 'Evidence-Based Interventions',
            'select_intervention_area': 'Select Intervention Area',
            'recommended_interventions': 'Recommended Interventions:',
            'research_statistics': 'Research Statistics',
            'prevalence_learning_difficulties': 'Prevalence of Learning Difficulties (%)',
            'key_research_findings': 'Key Research Findings:',
            'early_intervention_improves': 'Early intervention improves outcomes by 70%',
            'multi_sensory_effective': 'Multi-sensory approaches are most effective',
            'regular_monitoring_essential': 'Regular progress monitoring is essential',
            'family_involvement_doubles': 'Family involvement doubles success rates',
            'cultural_adaptation_increases': 'Cultural adaptation increases intervention effectiveness',
            'attention_issues': 'Attention Issues', 
            'category': 'Category', 
            'percentage': 'Percentage', 

            # Common Rating options 
            'poor': 'Poor',
            'below_average': 'Below Average',
            'average': 'Average',
            'good': 'Good',
            'excellent': 'Excellent',
            'low': 'Low',
            'medium': 'Medium',
            'high': 'High',
        },
        'Somali': {
            # Navigation
            'dashboard': 'Xarunta Xogta',
            'prediction': 'Qiimayn',
            'assessment': 'Qiimayn',  
            'resources': 'Agabka',
            'tracker': 'Dabagal',
            'analytics': 'Falanqayn',
            'settings': 'Dejinta',
            'educational_content': 'Waxbarasho', 

            # Header & Global Status
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'Barnaamijka Qiimaynta Barashada Xirfadlayaasha',
            'system_status': 'Xaaladda Nidaamka', 
            'online_mode': 'Hab Toos ah', 
            'offline_mode': 'Hab Offline ah', 
            'toggle_offline_mode': 'Beddel Habka Offline', 
            'new_assessment_button': 'Qiimayn Cusub', 

            # Dashboard - System Overview Stat Cards (Labels matching image text)
            'total_students_label': 'Wadarta Ardayda',
            'new_this_month_label': '↑ 12 cusub bishan', 
            'on_track_label': 'Waddada Saxda ah',
            'performing_well_label': '↑ 78% si fiican ayay u qabtaan', 
            'at_risk_label': 'Khatar',
            'need_support_label': '↑ 15% waxay u baahan yihiin taageero', 
            'intervention_label': 'Faragelin',
            'urgent_attention_label': '↑ 7% degdeg u baahan', 


            # Assessment Form
            'assessment_form': 'Foomka Qiimaynta',
            'empowering_student_success': 'Xoojinta Guulaha Ardayda',
            'student_information': 'Macluumaadka Ardayga',
            'grade_level': 'Heerka Fasalka',
            'teacher_name': 'Magaca Macallinka',
            'assessment_date': 'Taariikhda Qiimaynta',
            'academic_performance': 'Waxqabadka Tacliinta',
            'behavioral_social_indicators': 'Tilmaamaha Dhaqanka iyo Bulshada',
            'math_score': 'Dhibcaha Xisaabta (0-100)',
            'reading_score': 'Dhibcaha Akhriska (0-100)',  
            'writing_score': 'Dhibcaha Qorista (0-100)',
            'attendance': 'Soo Gaadhitaanka Dugsiga (%)',
            'behavior_rating': 'Qiimaynta Dhaqanka (1-5)', 
            'literacy_level': 'Heerka Aqrinta (1-10)', 
            'analyze_learning_risk': 'Falanqee Khatarta Barashada',
            'clear_form': 'Nadiifi Foomka',
            'assessment_results': 'Natiijada Qiimaynta AI',
            'comprehensive_assessment': 'Qiimayn dhamaystiran oo barasho ah ayaa loo dhammeeyay',
            'risk_level': 'Heerka Khatarta',
            'recommendations': 'Talooyinka',
            'low_risk': 'Khatar Yar',
            'medium_risk': 'Khatar Dhexdhexaad ah',
            'high_risk': 'Khatar Weyn',
            'confidence': 'Hubin',
            'teacher_notes': 'Xusuusta Macallinka',
            'prediction_saved_success': 'Qiimaynta si guul leh ayaa loo kaydiyay!',
            'prediction_save_error': 'Cilad ayaa ka timid kaydinta qiimaynta.',
            'model_not_available': 'Moodelka lama heli karo. Fadlan hubi faylasha moodelka.',
            'error_making_prediction': 'Cilad ayaa ka timid samaynta qiimaynta:',
            'is_performing_well': 'si fiican ayuu u qabanayaa. Sii wad hababka waxbarashada ee hadda jira.',
            'maintain_academic_support': 'Sii wad taageerada tacliinta ee hadda jirta',
            'consider_enrichment': 'Ka fiirso hawlaha kobcinta',
            'regular_monitoring': 'Kormeer joogto ah oo horumarka ah',
            'may_need_additional_support': 'waxaa laga yaabaa inuu u baahdo taageero dheeraad ah.',
            'provide_targeted_interventions': 'Bixi faragelin gaar ah',
            'increase_one_on_one': 'Kordhi taageerada qof-ka-qofka ah',
            'monitor_weekly': 'La soco horumarka toddobaadle',
            'requires_immediate_intervention': 'waxa uu u baahan yahay faragelin degdeg ah.',
            'implement_intensive_program': 'Hirgeli barnaamij taageero xooggan',
            'daily_monitoring': 'Kormeer maalinle ah oo horumarka ah',
            'consider_specialist': 'Ka fiirso qiimayn takhasusle',

            # Teacher Resources
            'teacher_resources': 'Agabka Macalliminta', 
            'supporting_every_teacher': 'Taageeridda Macallin kasta, Gaadhitaanka Arday Kasta',
            'inclusive_classroom_excellence': 'Fiicnaan Fasal oo Dhammaystiran',
            'professional_collaboration': 'Iskaashi Xirfadeed',
            'engaging_learning_strategies': 'Xeeladaha Barashada Soo Jiidashada leh',
            'assessment_innovation': 'Hal-abuurka Qiimaynta',
            'teaching_guides': 'Tilmaamaha iyo Xeeladaha Waxbarashada',
            'lesson_plans': 'Abuurista Qorshaha Casharrada',
            'educational_games': 'Ciyaaraha Waxbarasho',
            'real_life_activities': 'Dhaqdhaqaaqyada Nolosha Dhabta ah',
            'saved_resources': 'Agabka la Keydsaday',
            'excellence_in_education': 'Fiicnaanta Waxbarasho Soomaaliya',
            'empowering_teachers': 'Xoojinta Macalliminta iyada oo la adeegsanayo Xeeladaha Taageerada Barashada ee ku Salaysan Caddeyn',
            'professional_development': 'Agabka horumarinta xirfadeed ee loo qorsheeyay guulaha fasal dhammaystiran',
            'create_learning_environments': 'Samee deegaan barasho oo arday kasta ku kobco iyada oo la adeegsanayo tadris kala duwan',
            'build_strong_partnerships': 'Dhis iskaashi adag oo qoysaska iyo takhasusyada la sameeyo si loo helo taageero arday oo dhamaystiran',
            'implement_culturally_responsive': 'Hirgelinta hababka waxbarbarashada ee dhaqan-ogaanta leh ee la xidhiidha ardayda Soomaaliyeed',
            'use_multiple_assessment': 'Isticmaal hababka qiimayn ee kala duwan si si sax ah loogu cabbiro horumarka iyo baahiyaha ardayda',
            'teaching_excellence_showcase': 'Bandhigga Fiicnaanta Waxbarashada',
            'resource_categories': 'Qaybaha Agabka',
            'choose_resource_type': 'Dooro nooca agabka:',
            'differentiated_learning_strategies': 'Xeeladaha Barashada ee Kala Duwanaanta',
            'inclusive_classroom_tips': 'Talooyinka Fasal Dhammaystiran',
            'intervention_techniques': 'Farsamada Faragelinta',
            'assessment_strategies': 'Xeeladaha Qiimaynta',
            'activity_generator': 'Dhaliyaha Dhaqdhaqaaqa',
            'teaching_strategies': 'Xeeladaha Waxbarashada',
            'learning_activities': 'Dhaqdhaqaaqyada Barashada',
            'assessment_tools': 'Qalab Qiimayn',
            'classroom_management': 'Maamaynta Fasalka',
            'differentiation_techniques': 'Farsamada Kala-soocida',
            'technology_integration': 'Isku-dhafka Teknoolajiyada',
            'cultural_sensitivity': 'Dareen-ka Dhaqanka',
            'difficulty_focus': 'Diiradda Caqabadaha',
            'target_difficulty': 'Caqabadda bartilmaameedka ah:',
            'reading_language': 'Akhriska/Luqadda',
            'mathematics': 'Xisaabta',
            'writing': 'Qorista',
            'attention_focus': 'Diiradda/Feejignaan',
            'memory': 'Xusuusta',
            'processing_speed': 'Xawaaraha Farsamaynta',
            'social_skills': 'Xirfadaha Bulshada',
            'behavioral_issues': 'Arrimaha Dhaqanka',
            'generate_teaching_strategy': 'Soo saar Xeellad waxbarasho',
            'strategy_generated': 'Xeelladda waxbarashada waa la soo saaray!',
            'interactive_learning_activities': 'Hawlaha waxbarasho ee isdhexgalka',
            'generate_activity_ideas': 'Soo saar fikradaha hawlaha',
            'activity_ideas_generated': 'Fikradaha hawlaha waa la soo saaray!',
            'assessment_type': 'Nooca Qiimaynta',
            'create_assessment': 'Samee Qiimayn',
            'assessment_template_created': 'Qaabka qiimaynta waa la sameeyay!',
            'clear_learning_objectives': 'Ujeedooyinka waxbarashada oo cad la qeexay',
            'multiple_question_formats': 'Qaababka su\'aalaha kala duwan oo lagu daray',
            'rubric_provided': 'Habraaca qiimaynta oo la bixiyay',
            'differentiated_difficulty': 'Heerarka adag ee kala duwan oo la heli karo',
            'subject_area': 'Goobta Maaddada',

            # Parent Tracker
            'parent_tracker': 'Dabagalka Waalidka',
            'strengthening_connections': 'Xoojinta Xiriirka Guriga-Dugsiga',
            'daily_observation_log': 'Diiwaanka Indho-indhaynta Maalinta',
            'child_name': 'Magaca Ilmaha',
            'observation_date': 'Taariikhda Indho-indhaynta',
            'academic_observations': 'Indho-indhaynta Tacliinta',
            'homework_completion': 'Dhammaystirka Hawsha Guriga (%)',
            'reading_time': 'Waqtiga Akhriska (daqiiqado)',
            'focus_level': 'Heerka Diiradda',
            'subjects_struggled': 'Maadooyinka la Tacban yahay',
            'behavioral_observations': 'Indho-indhaynta Dhaqanka',
            'mood_rating': 'Qiimaynta Dareenka',
            'sleep_hours': 'Saacadaha Hurdada',
            'energy_level': 'Heerka Tamarta',
            'learning_wins': 'Guusha Barashada Maanta',
            'challenges_faced': 'Caqabadaha la Kulmay',
            'save_observation': 'Kaydi Indho-indhaynta',
            'progress_insights': 'Aragtiyo Horumarka',
            'supporting_childs_learning': 'Taageeridda Safarka Barashada Ilmahaaga',
            'family_centered_approach': 'Hab Qoys ku Aasaasan si loo Gaadho Guulaha Waxbarasho',
            'empowering_parents_tools': 'Xoojinta waalidka iyada oo la adeegsanayo qalab iyo aragtiyo si ay u taageeraan koboca tacliinta ilmahooda guriga',
            'monitor_child_progress': 'La-soco horumarka barashada ilmahaaga iyada oo la adeegsanayo qalab fudud oo waxtar leh',
            'parent_empowerment': 'Xoojinta Waalidka',
            'gain_insights_strategies': 'Hel aragtiyo iyo xeeladaho si aad ugu taageerto barashada guriga',
            'school_partnership': 'Iskaashiga Dugsiga',
            'build_communication_bridges': 'Dhis buundooyin wadahadal oo xooggan oo aad la samayso macalliminta ilmahaaga',
            'student_success': 'Guulaha Ardayga',
            'celebrate_achievements': 'U dabaal-deg guulaha oo wada xalli caqabadaha',
            'student_progress_stories': 'Sheekoooyinka Horumarka Ardayda',
            'child_selection': 'Doorashada Ilmaha',
            'tracking': 'Dabagal',
            'dashboard_options': 'Doorashooyinka Xarunta Xogta',
            'choose_view': 'Dooro aragtida:',
            'daily_entry': 'Gelinsa Maalinlaha ah',
            'progress_tracking': 'Dabagalka Horumarka',
            'weekly_summary': 'Soo-koobka Toddobaadlaha ah',
            'observations_log': 'Diiwaanka Indho-indhaynta',
            'observation_saved_success': 'Indho-indhaynta si guul leh ayaa loo kaydiyay!',
            'observation_save_error': 'Cilad ayaa ka timid kaydinta indho-indhaynta.',
            'no_observations_recorded': 'Weli lama diiwaan gelin wax indho-indhayn ah.',
            'error_loading_observations': 'Cilad ayaa ka timid soo dejinta indho-indhaynta:',
            'focus_level_trend': 'Isbeddelka Heerka Diiradda',
            'focus_level_over_time': 'Heerka Diiradda Waqtiyada kala duwan',
            'date': 'Taariikh', 
            'behavioral_emotional': 'Dhaqan & Dareen',

            # Educational Content
            'educational_content': 'Waxyaabaha Waxbarasho', 
            'building_educational_excellence': 'Dhisidda Fiicnaanta Waxbarasho iyada oo loo marayo Cilmi-baaris',
            'evidence_based_insights': 'Aragtiyo ku Salaysan Caddayn si loo Gaadho Guulaha Barashada',
            'comprehensive_educational_research': 'Cilmi-baaris dhamaystiran oo waxbarasho ah iyo agab taageerid ah si loo xoojijo faragelinta waxtar leh',
            'educational_excellence_in_action': 'Fiicnaanta Waxbarasho ee Ficilka ah',
            'global_best_practices': 'Hab-maamuuska Ugu Fiican Adduunka',
            'international_standards': 'Heerarka caalamiga ah iyo hababka loo waafajiyay jadada waxbarasho ee Soomaaliya',
            'learning_science': 'Sayniska Barashada',
            'neuroscience_cognitive_research': 'Cilmi-baarista maskaxda iyo fekerka oo ku saabsan sida caruurtu u bartaan si ugu waxtar badan',
            'intervention_studies': 'Daraasadaha Faragelinta',
            'evidence_based_strategies': 'Xeeladaha ku salaysan caddeyn si loo taageero ardayda leh caqabadaha barashada',
            'cultural_adaptation': 'La-qabsiga Dhaqanka',
            'implementing_inclusive_education': 'Cilmi-baaris ku saabsan hirgelinta waxbarasho dhammaystiran oo ku habboon jadad dhaqameed oo kala duwan',
            'educational_research_impact': 'Saameynta Cilmi-baarista Waxbarasho',
            'content_categories': 'Qaybaha Waxyaabaha',
            'choose_content_type': 'Dooro nooca waxyaabaha:',
            'research_overview': 'Dulmar Cilmi-baaris',
            'types_learning_difficulties': 'Noocyada Caqabadaha Barashada',
            'early_intervention': 'Faragelin Hore',
            'academic_resources': 'Agabka Tacliinta',
            'technology_tools': 'Qalab Teknoolajiyeed',
            'support_strategies': 'Xeeladaha Taageerada',
            'target_audience': 'Dadka Bartilmaameedka ah',
            'content_for': 'Waxyaabaha loogu talagalay:',
            'teachers': 'Macallimiin',
            'parents': 'Waalidiinta',
            'administrators': 'Maamuleyaasha',
            'all': 'Dhammaan',
            'understanding_learning_difficulties': 'Fahamka Caqabadaha Barashada',
            'learning_difficulties_affect_how': 'Caqabadaha barashadu waxay saameeyaan sida ardaydu u farsameeyaan oo u fahmaan macluumaadka. Aqoonsiga hore iyo faragelintu waa lama huraan guusha ardayga.',
            'common_types': 'Noocyada Caadiga ah:',
            'dyslexia': 'Diyseleksiya',
            'reading_difficulties': 'Caqabado akhris',
            'dyscalculia': 'Diysekalkuliya',
            'math_difficulties': 'Caqabado xisaab',
            'adhd': 'ADHD',
            'attention_difficulties': 'Caqabado feejignaan',
            'processing_disorders': 'Xanuunada farsamaynta',
            'information_processing_issues': 'Arrimaaha farsamaynta macluumaadka',
            'signs_to_watch_for': 'Calaamadaha la Fiirinayo:',
            'difficulty_following_instructions': 'Dhib ku qabashada tilmaamaha',
            'problems_reading_comprehension': 'Dhibaatooyinka fahamka akhriska',
            'trouble_math_concepts': 'Dhibaato la xiriirta fikradaha xisaabta',
            'difficulty_staying_focused': 'Dhib ku qabashada joogtaynta diiradda',
            'problems_writing_spelling': 'Dhibaatooyinka qorista iyo higgaadda',
            'evidence_based_interventions': 'Faragelin ku salaysan Caddeyn',
            'select_intervention_area': 'Dooro Goobta Faragelinta',
            'recommended_interventions': 'Faragelinta lagu Taliyay:',
            'research_statistics': 'Tirokoobka Cilmi-baarista',
            'prevalence_learning_difficulties': 'Faafitaanka Caqabadaha Barashada (%)',
            'key_research_findings': 'Natiijooyinka Muhiimka ah ee Cilmi-baarista:',
            'early_intervention_improves': 'Faragelinta hore waxay hagaajisaa natiijooyinka 70%',
            'multi_sensory_effective': 'Hababka dareenka badan ayaa ah kuwa ugu waxtarka badan',
            'regular_monitoring_essential': 'Kormeer joogto ah oo horumarka ah waa lama huraan',
            'family_involvement_doubles': 'Ka-qaybgalka qoysku wuxuu labanlaabaa heerarka guusha',
            'cultural_adaptation_increases': 'La-qabsiga dhaqanku wuxuu kordhiyaa waxtarka faragelinta',
            'attention_issues': 'Arrimaaha Feejignaan', 
            'category': 'Qayb', 
            'percentage': 'Boqolley', 

            # Common Rating options 
            'poor': 'Liita',
            'below_average': 'Ka hooseeya Celceliska',
            'average': 'Celcelis ah',
            'good': 'Fiican',
            'excellent': 'Aad u Fiican',
            'low': 'Hoose',
            'medium': 'Dhexdhexaad',
            'high': 'Sare',
        },
        'Arabic': {
            # Navigation
            'dashboard': 'لوحة التحكم',
            'prediction': 'التقييم',
            'assessment': 'التقييم',  
            'resources': 'الموارد',
            'tracker': 'المتتبع',
            'analytics': 'التحليلات',
            'settings': 'الإعدادات',
            'educational_content': 'محتوى تعليمي', 

            # Header & Global Status
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'تطبيق التقييم التعليمي المهني',
            'system_status': 'حالة النظام', 
            'online_mode': 'وضع الاتصال', 
            'offline_mode': 'وضع عدم الاتصال', 
            'toggle_offline_mode': 'تبديل وضع عدم الاتصال', 
            'new_assessment_button': 'تقييم جديد', 

            # Dashboard - System Overview Stat Cards (Labels matching image text)
            'total_students_label': 'إجمالي الطلاب',
            'new_this_month_label': '↑ 12 جديد هذا الشهر', 
            'on_track_label': 'في المسار الصحيح',
            'performing_well_label': '↑ 78% أداء جيد', 
            'at_risk_label': 'معرض للخطر',
            'need_support_label': '↑ 15% بحاجة للدعم', 
            'intervention_label': 'تدخل',
            'urgent_attention_label': '↑ 7% اهتمام عاجل', 


            # Assessment Form
            'assessment_form': 'نموذج التقييم',
            'empowering_student_success': 'تمكين نجاح الطلاب',
            'student_information': 'معلومات الطالب',
            'grade_level': 'مستوى الصف',
            'teacher_name': 'اسم المعلم', 
            'assessment_date': 'تاريخ التقييم', 
            'academic_performance': 'الأداء الأكاديمي',
            'behavioral_social_indicators': 'المؤشرات السلوكية والاجتماعية',
            'math_score': 'درجة الرياضيات (0-100)',
            'reading_score': 'درجة القراءة (0-100)',  
            'writing_score': 'درجة الكتابة (0-100)',
            'attendance': 'حضور المدرسة (%)',
            'behavior_rating': 'تقييم السلوك (1-5)', 
            'literacy_level': 'مستوى محو الأمية (1-10)', 
            'analyze_learning_risk': 'تحليل مخاطر التعلم',
            'clear_form': 'مسح النموذج',
            'assessment_results': 'نتائج تقييم الذكاء الاصطناعي',
            'comprehensive_assessment': 'تم إكمال تقييم تعليمي شامل لـ',
            'risk_level': 'مستوى المخاطر',
            'recommendations': 'التوصيات',
            'low_risk': 'مخاطر منخفضة',
            'medium_risk': 'مخاطر متوسطة',
            'high_risk': 'مخاطر عالية',
            'confidence': 'ثقة',
            'teacher_notes': 'ملاحظات المعلم',
            'prediction_saved_success': 'تم حفظ التقييم بنجاح!',
            'prediction_save_error': 'خطأ في حفظ التقييم.',
            'model_not_available': 'النموذج غير متاح. يرجى التحقق من ملفات النموذج.',
            'error_making_prediction': 'خطأ في إجراء التقييم:',
            'is_performing_well': 'يقدم أداءً جيدًا. استمر في طرق التدريس الحالية.',
            'maintain_academic_support': 'الحفاظ على الدعم الأكاديمي الحالي',
            'consider_enrichment': 'النظر في الأنشطة الإثرائية',
            'regular_monitoring': 'المراقبة المنتظمة للتقدم',
            'may_need_additional_support': 'قد يحتاج إلى دعم إضافي.',
            'provide_targeted_interventions': 'تقديم تدخلات موجهة',
            'increase_one_on_one': 'زيادة الدعم الفردي',
            'monitor_weekly': 'مراقبة التقدم أسبوعيا',
            'requires_immediate_intervention': 'يتطلب تدخلاً فورياً.',
            'implement_intensive_program': 'تنفيذ برنامج دعم مكثف',
            'daily_monitoring': 'المراقبة اليومية للتقدم',
            'consider_specialist': 'النظر في تقييم متخصص',

            # Teacher Resources
            'teacher_resources': 'موارد المعلمين', 
            'supporting_every_teacher': 'دعم كل معلم، الوصول إلى كل طالب',
            'inclusive_classroom_excellence': 'التميز في الفصل الدراسي الشامل',
            'professional_collaboration': 'التعاون المهني',
            'engaging_learning_strategies': 'استراتيجيات التعلم الجذابة',
            'assessment_innovation': 'ابتكار التقييم',
            'teaching_guides': 'أدلة واستراتيجيات التدريس',
            'lesson_plans': 'إنشاء خطط الدروس',
            'educational_games': 'الألعاب التعليمية',
            'real_life_activities': 'أنشطة التعلم الواقعية',
            'saved_resources': 'الموارد المحفوظة',
            'excellence_in_education': 'التميز في التعليم الصومالي',
            'empowering_teachers': 'تمكين المعلمين باستراتيجيات دعم التعلم القائمة على الأدلة',
            'professional_development': 'موارد التطوير المهني المصممة لنجاح الفصول الدراسية الشاملة',
            'create_learning_environments': 'إنشاء بيئات تعليمية يزدهر فيها كل طالب من خلال التدريس المتمايز',
            'build_strong_partnerships': 'بناء شراكات قوية مع الأسر والمتخصصين لدعم الطلاب الشامل',
            'implement_culturally_responsive': 'تنفيذ أساليب تدريس مستجيبة ثقافياً تتواصل مع الطلاب الصوماليين',
            'use_multiple_assessment': 'استخدام أساليب تقييم متعددة لقياس تقدم الطلاب واحتياجاتهم بدقة',
            'teaching_excellence_showcase': 'معرض التميز في التدريس',
            'resource_categories': 'فئات الموارد',
            'choose_resource_type': 'اختر نوع المورد:',
            'differentiated_learning_strategies': 'استراتيجيات التعلم المتمايزة',
            'inclusive_classroom_tips': 'نصائح الفصل الدراسي الشامل',
            'intervention_techniques': 'تقنيات التدخل',
            'assessment_strategies': 'استراتيجيات التقييم',
            'activity_generator': 'مولد الأنشطة',
            'teaching_strategies': 'استراتيجيات التدريس',
            'learning_activities': 'أنشطة التعلم',
            'assessment_tools': 'أدوات التقييم',
            'classroom_management': 'إدارة الفصل الدراسي',
            'differentiation_techniques': 'تقنيات التمايز',
            'technology_integration': 'دمج التكنولوجيا',
            'cultural_sensitivity': 'الحساسية الثقافية',
            'difficulty_focus': 'تركيز الصعوبة',
            'target_difficulty': 'الصعوبة المستهدفة:',
            'reading_language': 'القراءة/اللغة',
            'mathematics': 'الرياضيات',
            'writing': 'الكتابة',
            'attention_focus': 'الانتباه/التركيز',
            'memory': 'الذاكرة',
            'processing_speed': 'سرعة المعالجة',
            'social_skills': 'المهارات الاجتماعية',
            'behavioral_issues': 'المشكلات السلوكية',
            'generate_teaching_strategy': 'توليد استراتيجية التدريس',
            'strategy_generated': 'تم توليد استراتيجية التدريس!',
            'interactive_learning_activities': 'أنشطة التعلم التفاعلية',
            'generate_activity_ideas': 'توليد أفكار النشاط',
            'activity_ideas_generated': 'تم توليد أفكار النشاط!',
            'assessment_type': 'نوع التقييم',
            'create_assessment': 'إنشاء تقييم',
            'assessment_template_created': 'تم إنشاء قالب التقييم!',
            'clear_learning_objectives': 'أهداف تعلم واضحة محددة',
            'multiple_question_formats': 'صيغ أسئلة متعددة متضمنة',
            'rubric_provided': 'تم توفير نموذج للتقييم',
            'differentiated_difficulty': 'مستويات صعوبة متمايزة متاحة',
            'subject_area': 'المادة الدراسية',

            # Parent Tracker
            'parent_tracker': 'متتبع الوالدين',
            'strengthening_connections': 'تعزيز الروابط بين المنزل والمدرسة',
            'daily_observation_log': 'سجل الملاحظة اليومية',
            'child_name': 'اسم الطفل',
            'observation_date': 'تاريخ الملاحظة',
            'academic_observations': 'الملاحظات الأكاديمية',
            'homework_completion': 'إنجاز الواجبات المنزلية (%)',
            'reading_time': 'وقت القراءة (دقائق)',
            'focus_level': 'مستوى التركيز',
            'subjects_struggled': 'المواد التي واجه صعوبة فيها',
            'behavioral_observations': 'الملاحظات السلوكية',
            'mood_rating': 'تقييم المزاج',
            'sleep_hours': 'ساعات النوم',
            'energy_level': 'مستوى الطاقة',
            'learning_wins': 'انتصارات التعلم اليوم',
            'challenges_faced': 'التحديات المواجهة',
            'save_observation': 'حفظ الملاحظة',
            'progress_insights': 'رؤى التقدم',
            'supporting_childs_learning': 'دعم رحلة تعلم طفلك',
            'family_centered_approach': 'نهج يركز على الأسرة لتحقيق النجاح التعليمي',
            'empowering_parents_tools': 'تمكين الآباء بالأدوات والرؤى لدعم النمو الأكاديمي لأطفالهم في المنزل',
            'monitor_child_progress': 'مراقبة تقدم تعلم طفلك باستخدام أدوات بسيطة وفعالة',
            'parent_empowerment': 'تمكين الوالدين',
            'gain_insights_strategies': 'اكتساب رؤى واستراتيجيات لدعم التعلم في المنزل',
            'school_partnership': 'الشراكة المدرسية',
            'build_communication_bridges': 'بناء جسور اتصال قوية مع معلمي طفلك',
            'student_success': 'نجاح الطالب',
            'celebrate_achievements': 'الاحتفال بالإنجازات ومعالجة التحديات معًا',
            'student_progress_stories': 'قصص تقدم الطلاب',
            'child_selection': 'اختيار الطفل',
            'tracking': 'التتبع',
            'dashboard_options': 'خيارات لوحة التحكم',
            'choose_view': 'اختر العرض:',
            'daily_entry': 'إدخال يومي',
            'progress_tracking': 'تتبع التقدم',
            'weekly_summary': 'ملخص أسبوعي',
            'observations_log': 'سجل الملاحظات',
            'observation_saved_success': 'تم حفظ الملاحظة بنجاح!',
            'observation_save_error': 'خطأ في حفظ الملاحظة.',
            'no_observations_recorded': 'لم يتم تسجيل أي ملاحظات بعد.',
            'error_loading_observations': 'خطأ في تحميل الملاحظات:',
            'focus_level_trend': 'اتجاه مستوى التركيز',
            'focus_level_over_time': 'مستوى التركيز بمرور الوقت',
            'date': 'التاريخ', 
            'behavioral_emotional': 'السلوكي والعاطفي',

            # Educational Content
            'educational_content': 'المحتوى التعليمي', 
            'building_educational_excellence': 'بناء التميز التعليمي من خلال البحث',
            'evidence_based_insights': 'رؤى قائمة على الأدلة لنجاح التعلم',
            'comprehensive_educational_research': 'بحث تعليمي شامل وموارد لدعم التدخلات التعليمية الفعالة',
            'educational_excellence_in_action': 'التميز التعليمي في العمل',
            'global_best_practices': 'أفضل الممارسات العالمية',
            'international_standards': 'المعايير الدولية والأساليب المكيفة للبيئات التعليمية الصومالية',
            'learning_science': 'علم التعلم',
            'neuroscience_cognitive_research': 'أبحاث علم الأعصاب والإدراك حول كيفية تعلم الأطفال بشكل أكثر فعالية',
            'intervention_studies': 'دراسات التدخل',
            'evidence_based_strategies': 'استراتيجيات قائمة على الأدلة لدعم الطلاب ذوي تحديات التعلم',
            'cultural_adaptation': 'التكيف الثقافي',
            'implementing_inclusive_education': 'بحث حول تنفيذ التعليم الشامل في سياقات ثقافية متنوعة',
            'educational_research_impact': 'أثر البحث التعليمي',
            'content_categories': 'فئات المحتوى',
            'choose_content_type': 'اختر نوع المحتوى:',
            'research_overview': 'نظرة عامة على البحث',
            'types_learning_difficulties': 'أنواع صعوبات التعلم',
            'early_intervention': 'التدخل المبكر',
            'academic_resources': 'الموارد الأكاديمية',
            'technology_tools': 'أدوات التكنولوجيا',
            'support_strategies': 'استراتيجيات الدعم',
            'target_audience': 'الجمهور المستهدف',
            'content_for': 'المحتوى لـ:',
            'teachers': 'المعلمين',
            'parents': 'الآباء',
            'administrators': 'الإداريين',
            'all': 'الجميع',
            'understanding_learning_difficulties': 'فهم صعوبات التعلم',
            'learning_difficulties_affect_how': 'تؤثر صعوبات التعلم على كيفية معالجة الطلاب للمعلومات وفهمها. التحديد المبكر والتدخل أمران حاسمان لنجاح الطالب.',
            'common_types': 'الأنواع الشائعة:',
            'dyslexia': 'عسر القراءة',
            'reading_difficulties': 'صعوبات القراءة',
            'dyscalculia': 'عسر الحساب',
            'math_difficulties': 'صعوبات الرياضيات',
            'adhd': 'اضطراب فرط الحركة ونقص الانتباه',
            'attention_difficulties': 'صعوبات الانتباه',
            'processing_disorders': 'اضطرابات المعالجة',
            'information_processing_issues': 'مشاكل معالجة المعلومات',
            'signs_to_watch_for': 'علامات يجب الانتباه إليها:',
            'difficulty_following_instructions': 'صعوبة في اتباع التعليمات',
            'problems_reading_comprehension': 'مشاكل في فهم القراءة',
            'trouble_math_concepts': 'مشكلة في مفاهيم الرياضيات',
            'difficulty_staying_focused': 'صعوبة في البقاء مركزاً',
            'problems_writing_spelling': 'مشاكل في الكتابة والتهجئة',
            'evidence_based_interventions': 'التدخلات القائمة على الأدلة',
            'select_intervention_area': 'اختر مجال التدخل',
            'recommended_interventions': 'التدخلات الموصى بها:',
            'research_statistics': 'إحصائيات البحث',
            'prevalence_learning_difficulties': 'انتشار صعوبات التعلم (%)',
            'key_research_findings': 'نتائج البحث الرئيسية:',
            'early_intervention_improves': 'التدخل المبكر يحسن النتائج بنسبة 70%',
            'multi_sensory_effective': 'النهج متعدد الحواس هو الأكثر فعالية',
            'regular_monitoring_essential': 'المراقبة المنتظمة للتقدم ضرورية',
            'family_involvement_doubles': 'مشاركة الأسرة تضاعف معدلات النجاح',
            'cultural_adaptation_increases': 'التكيف الثقافي يزيد من فعالية التدخل',
            'attention_issues': 'مشاكل الانتباه', 
            'category': 'الفئة', 
            'percentage': 'النسبة المئوية', 

            # Common Rating options 
            'poor': 'ضعيف',
            'below_average': 'أقل من المتوسط',
            'average': 'متوسط',
            'good': 'جيد',
            'excellent': 'ممتاز',
            'low': 'منخفض',
            'medium': 'متوسط',
            'high': 'عالي',
        }
    }
    
    return translations.get(language, translations['English']).get(key, key)